### ISSUE TITLE
Modification of Paneron Register Metadata type to support modelling with Lutaml Model

### ISSUE THREAD

**Issue by ribose-jeffreylau** [paneron/paneron#127]
## Motivation

There is an [ongoing effort](https://github.com/paneron/ruby-paneron-register) to model a Paneron register using [lutaml-model](https://github.com/lutaml/lutaml-model).  The general approach is to look at the Typescript types defined in [paneron (this repo)](https://github.com/paneron/paneron), and try to replicate (as close as possible) the structure in Lutaml.

All is well except for a place (`paneron.yaml`) in the register's metadata that defines `datasets`, _i.e._,

```yaml
---
title: registry title
datasets:
  my-dataset-path: true
  my-dataset2-path: true

```

... which corresponds to:

https://github.com/paneron/paneron/blob/61091425a06bbee74d6dd350ac4fc86403801d2c/src/repositories/types.ts#L12-L20

The issue is that Lutaml Model is not able to model keyed collections where the values are not themselves models, but primitive types.

A suggestion (https://github.com/lutaml/lutaml-model/discussions/325#discussioncomment-12252668) is to model the above like so:

```yaml
---
title: registry title
datasets:
  my-dataset-path:
    available: true
  my-dataset2-path:
    available: true

```

Now, the values of `datasets:` hash is not a primitive value anymore, and can be modelled in Lutaml Model.

Assuming that Lutaml Model will not support the initial scenario, there is a way forward:

### Proposal

We can modify how Paneron:

- ingests `paneron.yaml` so that both ways are accepted;
- creates the initial `paneron.yaml` so the suggested modelling approach is used;
- <s>processes a register so it automatically updates `paneron.yaml` to use the suggested modelling approach.</s> (<- This could break older setups with Paneron stuck to an older version.)

The result is that:

- existing Paneron registers continue to work with Paneron;
- newly created registers using Paneron can be read by tools limited by Lutaml Model.

##### 1

https://github.com/paneron/paneron/blob/61091425a06bbee74d6dd350ac4fc86403801d2c/src/datasets/main/index.ts#L440

... can be changed into:

```typescript
 if (!repoMeta.datasets?.[datasetID]?.available) { 
```

##### 2

https://github.com/paneron/paneron/blob/61091425a06bbee74d6dd350ac4fc86403801d2c/src/repositories/types.ts#L12-L20

... will need to allow for the additional layer of data:

```typescript
export type PaneronRepository = {
  title?: string
} & ({
  datasets: { [path: string]: true | { available: true } }  // <--
  dataset?: undefined
} | {
  datasets?: undefined
  dataset: true
})
```

##### 3

And if we ever decide that Paneron will be responsible for migrating `paneron.yaml`,

https://github.com/paneron/paneron/blob/release/src/main/meta-serdes.ts#L1-L12

... will need to be modified to emit `datasets: { [path: string]: { available: true }}` in the `serializeMeta()` function, possibly before passing to `yaml.dump()`.

**Comment by ribose-jeffreylau** [comment]
cc @ronaldtse @strogonoff Would like to know your thoughts.  If it looks OK, I can proceed with the changes.

**Comment by ronaldtse** [comment]
@ribose-jeffreylau I have to say that this:

```yaml
---
title: registry title
datasets:
  my-dataset-path: true
  my-dataset2-path: true
```

Is very weird. Let's change it. You could even do this for simplicity. 

```yaml
---
title: registry title
datasets:
  - my-dataset-path
  - my-dataset2-path
```
